### ISSUE TITLE
Dependencies not listed

### ISSUE THREAD

**Issue by gexijin** [athril/runibic#6]
Hi Patryk,
Thanks for developing this package. 
I run into problems while trying to install the package. 
First, the Rtools needs to be installed. I did that following http://jtleek.com/modules/01_DataScientistToolbox/02_10_rtools/#1
This perhaps should be included in your tutorial. 

Then, it complains about  
"dependency 'Rcpp' is not available for package 'runibic' "
I deleted my old Rcpp folder and was able to make it work. 

I suggest you test install this package on a new computer and see if it runs. 
Thanks again. 

Xijin Ge

**Comment by athril** [comment]
Hi Xijin,

Thank you for raising this.  I'm glad you got our package working!

Are you on Windows?  Which version of R and Bioconductor are you using?
What is your `sessionInfo()`?

Your problems might have been related to Rcpp installation. 

Let's wait and see if this issue is present with new Bioconductor 3.6 release. The installation of our package might be simplified then.

Has anyone else encountered similar issues? 

Best
Patryk

**Comment by gexijin** [comment]
Patryk,
I am trying to make runibic part of a shiny app that users can run biclustering without programming. It’s  http://ge-lab.org/idep/

I am on windows. I also made it to work on Linux.
Thanks.
Xijin
P.S.
Here is my note:
1.       Install devtools   https://cran.r-project.org/web/packages/devtools/README.html
Linux:
o    Install the release version of devtools from CRAN with install.packages("devtools").
o    devtools::install_github("hadley/devtools")
Windows:
o    install.packages("devtools")
o    Install Rtools: https://cran.r-project.org/bin/windows/Rtools/

2.       Update devtools
devtools::install_github("hadley/devtools")

3.       Install remotes package
source("https://raw.githubusercontent.com/r-lib/remotes/master/install-github.R")$value("r-lib/remotes")
From <https://github.com/r-lib/remotes#installation>
This is needed to overcome an error related to callr.
4.       Install needed packages like Rcpp using install.packages("Rcpp"), if complained
5.       Install runibic <https://github.com/athril/runibic/>
remotes::install_github("athril/runibic")
From <https://github.com/r-lib/remotes#installation>


My session info on Windows:
R version 3.4.1 (2017-06-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C
[5] LC_TIME=English_United States.1252

attached base packages:
[1] parallel  stats4    grid      stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] runibic_0.99.14            SummarizedExperiment_1.6.5 DelayedArray_0.2.7
 [4] matrixStats_0.52.2         Biobase_2.36.2             GenomicRanges_1.28.5
 [7] GenomeInfoDb_1.12.2        IRanges_2.10.3             S4Vectors_0.14.4
[10] BiocGenerics_0.22.0        biclust_1.2.0              lattice_0.20-35
[13] colorspace_1.3-2           MASS_7.3-47

loaded via a namespace (and not attached):
[1] Rcpp_0.12.13            magrittr_1.5            XVector_0.16.0          knitr_1.17
 [5] zlibbioc_1.22.0         devtools_1.13.3         flexclust_1.3-4         R6_2.2.2
 [9] httr_1.3.1              tools_3.4.1             git2r_0.19.0            withr_2.0.0
[13] modeltools_0.2-21       digest_0.6.12           crayon_1.3.4            Matrix_1.2-11
[17] GenomeInfoDbData_0.99.0 bitops_1.0-6            testthat_1.0.2          RCurl_1.95-4.8
[21] curl_2.8.1              memoise_1.1.0           compiler_3.4.1          BiocIns

**Comment by athril** [comment]
Thank you Xijin for sharing your workaround. You've built a really great app!

If I manage to reproduce it or anyone else has similar issues, I've definitely include it in our tutorial.
I was planning to update documentation anyway when the new Bioconductor 3.6 is released (this should happen by the end of the day). 

I'm leaving this issue open for now.

Best
Patryk

**Comment by athril** [comment]
btw. I'm not sure if you need to install remotes package. 
The easier way is to install it using
`devtools::install_github("athril/runibic")`

**Comment by gexijin** [comment]
devtools::install_github("athril/runibic"
This will give me an error on Linux.
The error has something to do with “callr”:
Installation failed: 'rcmd_safe_env' is not an exported object from 'namespace:callr'
Using remotes package, I resolved it following the instructions at https://github.com/r-lib/callr/issues/17
.

**Comment by gexijin** [comment]
With Bioconductor 3.6, installation was smooth with no issues.
