### ISSUE TITLE
runibic detects correlated columns instead of rows

### ISSUE THREAD

**Issue by athril** [athril/runibic#8]
The following example shows the issue:
```
library(runibic)
library(gplots)
library(ALL)
data("ALL")
ALL
res<-runibic(exprs(ALL[1:100,]))
my<-bicluster(exprs(ALL[1:100,]),res,2)
heatmap.2(as.matrix(data.frame(my)), Colv=FALSE, Rowv=FALSE, dendrogram="none",density.info=c("none"), trace="none", margins=c(6,11))

```
As the result, detected patterns are transposed. Instead of finding genes that are correlated across samples, the algorithm actually finds samples that are correlated with each other across genes.

**Comment by Archi0** [comment]
Fixed in recent commit with better management of default parameters.
